-- CreateTable
CREATE TABLE "Widget" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "tab_id" INTEGER NOT NULL,
    "type" TEXT NOT NULL,
    "x" INTEGER NOT NULL,
    "y" INTEGER NOT NULL,
    "width" INTEGER NOT NULL,
    "height" INTEGER NOT NULL,
    CONSTRAINT "Widget_tab_id_fkey" FOREIGN KEY ("tab_id") REFERENCES "Tab" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
